// Date: 12/27/2013 1:26:08 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.pixelutilitys.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ClothedTableModel extends ModelBase
{
  //fields
    ModelRenderer TableTop;
    ModelRenderer LegFrontRight;
    ModelRenderer LegFrontLeft;
    ModelRenderer LegBackLeft;
    ModelRenderer LegBackRight;
  
  public ClothedTableModel()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      TableTop = new ModelRenderer(this, 0, 28);
      TableTop.addBox(-8F, -2F, -8F, 32, 4, 32);
      TableTop.setRotationPoint(0F, 8F, 0F);
      TableTop.setTextureSize(128, 64);
      TableTop.mirror = true;
      setRotation(TableTop, 0F, 0F, 0F);
      LegFrontRight = new ModelRenderer(this, 0, 0);
      LegFrontRight.addBox(-4F, 2F, -5F, 4, 14, 4);
      LegFrontRight.setRotationPoint(0F, 8F, 0F);
      LegFrontRight.setTextureSize(128, 64);
      LegFrontRight.mirror = true;
      setRotation(LegFrontRight, 0F, 0F, 0F);
      LegFrontLeft = new ModelRenderer(this, 0, 0);
      LegFrontLeft.addBox(16F, 2F, -5F, 4, 14, 4);
      LegFrontLeft.setRotationPoint(0F, 8F, 0F);
      LegFrontLeft.setTextureSize(128, 64);
      LegFrontLeft.mirror = true;
      setRotation(LegFrontLeft, 0F, 0F, 0F);
      LegBackLeft = new ModelRenderer(this, 0, 0);
      LegBackLeft.addBox(16F, 2F, 16F, 4, 14, 4);
      LegBackLeft.setRotationPoint(0F, 8F, 0F);
      LegBackLeft.setTextureSize(128, 64);
      LegBackLeft.mirror = true;
      setRotation(LegBackLeft, 0F, 0F, 0F);
      LegBackRight = new ModelRenderer(this, 0, 0);
      LegBackRight.addBox(-4F, 2F, 16F, 4, 14, 4);
      LegBackRight.setRotationPoint(0F, 8F, 0F);
      LegBackRight.setTextureSize(128, 64);
      LegBackRight.mirror = true;
      setRotation(LegBackRight, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    TableTop.render(f5);
    LegFrontRight.render(f5);
    LegFrontLeft.render(f5);
    LegBackLeft.render(f5);
    LegBackRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
