package com.pixelutilitys.config;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fluids.Fluid;

import com.pixelutilitys.blocks.*;
import com.pixelutilitys.creativetabs.PixelUtilitysCreativeTabs;
import com.pixelutilitys.ores.*;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class PixelUtilitysBlocks {

	public static int NewGrassBlockID;
	public static int PokeDirtBlockID;
	public static int PokeSandBlockID;
	public static int PokeSandC1BlockID;
	public static int PokeSandC2BlockID;
	public static int PokeSandC3BlockID;
	public static int PokeSandC4BlockID;
	public static int InsideMoldingBlockID;
	public static int PixelmonGrassBlockID;
	public static int ShinglesBlockID;
	public static int ShinglesCorner1BlockID;
	public static int ShinglesCorner2BlockID;
	public static int TreeTopBlockID;
	public static int TreeBottomBlockID;
	public static int PokeSandSide1BlockID;
	public static int PokeSandSide2BlockID;
	public static int PokeSandSide3BlockID;
	public static int PokeSandSide4BlockID;
	public static int Window1BlockID;
	public static int Window2BlockID;
	public static int WoodenFlooringBlockID;
	public static int PokeCenterSignBlockID;
	public static int PokeMartSignBlockID;
	public static int SandyGrassBlockID;
	public static int RockBlockID;
	public static int CaveRockBlockID;
	public static int BridgeBlockBlockID;
	public static int TreeBlockID;
	public static int BolderBlockID;
	public static int BoxBlockID;
	public static int RubyOreID;
	public static int SaphireOreID;
	public static int AmethystOreID;
	public static int CrystalOreID;
	public static int RubyBlockID;
	public static int SaphireBlockID;
	public static int AmethystBlockID;
	public static int CrystalBlockID;
	public static int SiliconOreID;
	public static int ClothedTableBlockID;
	public static int PokeballBlockID;
	public static int RedCusionChairBlockID;
	public static int TrashcanBlockID;
	public static int YellowCusionChairBlockID;
	public static int BasicDeskBlockID;
	public static int TotodilePokedollBlockID;
	//public static int PokeWaterStillID;
	//public static Fluid PokeWaterFlowingID;
	public static int AronPokedollBlockID;
	public static int BisharpPokedollBlockID;
	public static int BlockRadioID;
	//Blocks

	public static Block NewGrassBlock;
	public static Block PokeDirtBlock;
	public static Block PokeSandBlock;
	public static Block PokeSandC1Block;
	public static Block PokeSandC2Block;
	public static Block PokeSandC3Block;
	public static Block PokeSandC4Block;
	public static Block InsideMoldingBlock;
	public static Block PixelmonGrassBlock;
	public static Block ShinglesBlock;
	public static Block ShinglesCorner1Block;
	public static Block ShinglesCorner2Block;
	public static Block TreeTopBlock;
	public static Block TreeBottomBlock;
	public static Block PokeSandSide1Block;
	public static Block PokeSandSide2Block;
	public static Block PokeSandSide3Block;
	public static Block PokeSandSide4Block;
	public static Block Window1Block;
	public static Block Window2Block;
	public static Block WoodenFlooringBlock;
	public static Block PokeCenterSignBlock;
	public static Block PokeMartSignBlock;
	public static Block SandyGrassBlock;
	public static Block RockBlock;
	public static Block CaveRockBlock;
	public static Block BridgeBlockBlock;
	public static Block TreeBlock;
	public static Block BolderBlock;
	public static Block BoxBlock;
	public static Block RubyOre;
	public static Block SaphireOre;
	public static Block AmethystOre;
	public static Block CrystalOre;
	public static Block RubyBlock;
	public static Block SaphireBlock;
	public static Block AmethystBlock;
	public static Block CrystalBlock;
	public static Block SiliconOre;
	public static Block ClothedTableBlock;
	public static Block PokeballBlock;
	public static Block RedCusionChairBlock;
	public static Block TrashcanBlock;
	public static Block YellowCusionChairBlock;
	//public static Block BasicDeskBlock;
	public static Block TotodilePokedollBlock;
	public static Block AronPokedollBlock;
	public static Block BisharpPokedollBlock;
	public static Block RadioBlock;



	//public static Block PokeWaterStill;
	//public static Block PokeWaterFlowing;


	public static void load(Configuration cfg){

		NewGrassBlockID = cfg.get("block", "newgrass", 3050).getInt();
		PokeDirtBlockID = cfg.get("block", "pokedirt", 3051).getInt();
		PokeSandBlockID = cfg.get("block", "pokesand", 3052).getInt();
		PokeSandC1BlockID = cfg.get("block", "pokesandc1", 3053).getInt();
		PokeSandC2BlockID = cfg.get("block", "pokesandc2", 3054).getInt();
		PokeSandC3BlockID = cfg.get("block", "pokesandc3", 3055).getInt();
		PokeSandC4BlockID = cfg.get("block", "pokesandc4", 3056).getInt();
		InsideMoldingBlockID = cfg.get("block", "insidemolding", 3057).getInt();
		PixelmonGrassBlockID = cfg.get("block", "pixelmongrass", 3058).getInt();
		ShinglesBlockID = cfg.get("block", "shingles", 3059).getInt();
		ShinglesCorner1BlockID = cfg.get("block", "shinglescorner1", 3060).getInt();
		ShinglesCorner2BlockID = cfg.get("block", "shinglescorner2", 3061).getInt();
		TreeTopBlockID = cfg.get("block", "treetop", 3062).getInt();
		TreeBottomBlockID = cfg.get("block", "treebottom", 3063).getInt();
		PokeSandSide1BlockID = cfg.get("block", "pokesands1", 3064).getInt();
		PokeSandSide2BlockID = cfg.get("block", "pokesands2", 3065).getInt();
		PokeSandSide3BlockID = cfg.get("block", "pokesands3", 3066).getInt();
		PokeSandSide4BlockID = cfg.get("block", "pokesands4", 3067).getInt();
		Window1BlockID = cfg.get("block", "window1", 3068).getInt();
		Window2BlockID = cfg.get("block", "window2", 3069).getInt();
		WoodenFlooringBlockID = cfg.get("block", "woodenflooring", 3070).getInt();
		PokeCenterSignBlockID = cfg.get("block", "pokecentersign", 3071).getInt();
		PokeMartSignBlockID = cfg.get("block", "pokemartsign", 3072).getInt();
		SandyGrassBlockID = cfg.get("block", "sandygrass", 3073).getInt();
		RockBlockID = cfg.get("block", "rock", 3074).getInt();
		CaveRockBlockID = cfg.get("block", "caverock", 3075).getInt();
		BridgeBlockBlockID = cfg.get("block", "bridgeblock", 3076).getInt();
		TreeBlockID = cfg.get("block", "tree", 3077).getInt();
		BolderBlockID = cfg.get("block", "bolder", 3078).getInt();
		BoxBlockID = cfg.get("block", "box", 3079).getInt();
		RubyOreID = cfg.get("block", "rubyore", 3080).getInt();
		SaphireOreID = cfg.get("block", "saphireore", 3081).getInt();
		AmethystOreID = cfg.get("block", "amethystore", 3082).getInt();
		RubyBlockID = cfg.get("block", "rubyblock", 3083).getInt();
		SaphireBlockID = cfg.get("block", "saphireblock", 3084).getInt();
		AmethystBlockID = cfg.get("block", "amethystblock", 3085).getInt();
		SiliconOreID = cfg.get("block", "siliconore", 3086).getInt();
		ClothedTableBlockID = cfg.get("block", "clothedtable", 3089).getInt();
		PokeballBlockID = cfg.get("block", "pokeball", 3090).getInt();
		RedCusionChairBlockID = cfg.get("block", "redcusionchair", 3091).getInt();
		TrashcanBlockID = cfg.get("block", "trashcan", 3092).getInt();
		YellowCusionChairBlockID = cfg.get("block", "yellowcusionchair", 3093).getInt();
		TotodilePokedollBlockID = cfg.get("block", "totodiledoll", 3094).getInt();
		//PokeWaterFlowingID = cfg.get("block", "pokewaterflowing", 3095).getInt();
		//PokeWaterStillID = cfg.get("block", "pokewaterstill", 3096).getInt();
		AronPokedollBlockID = cfg.get("block", "arondoll", 3097).getInt();
		BisharpPokedollBlockID = cfg.get("block", "bisharpdoll", 3098).getInt();
		CrystalOreID = cfg.get("block", "crystalore", 3099).getInt();
		CrystalBlockID = cfg.get("block", "crystalblock", 3100).getInt();
		BlockRadioID = cfg.get("block", "radio", 3101).getInt();

		NewGrassBlock = new PokeGrassBlock(NewGrassBlockID, Material.grass).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("PokeGrass").setBlockTextureName("PixelUtilitys" +":"+ "PokeGrass").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks);;
		PokeDirtBlock = new PokeDirtBlock(PokeDirtBlockID, Material.grass).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("PokeDirt").setBlockTextureName("PixelUtilitys" +":"+ "PokeDirt").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks);;
		PokeSandBlock = new PokeSandBlock(PokeSandBlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSand").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "pokesand");;
		PokeSandC1Block = new PokeSandC1Block(PokeSandC1BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandCorner1").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "PokeSandC1");;
		PokeSandC2Block = new PokeSandC2Block(PokeSandC2BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandCorner2").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "PokeSandC2");;
		PokeSandC3Block = new PokeSandC3Block(PokeSandC3BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandCorner3").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "PokeSandC3");;
		PokeSandC4Block = new PokeSandC4Block(PokeSandC4BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandCorner4").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "PokeSandC4");;
		InsideMoldingBlock = new InsideMoldingBlock(InsideMoldingBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Inside Wall Molding").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "InsideMolding");;
		PixelmonGrassBlock = new PixelmonGrassBlock(PixelmonGrassBlockID, Material.grass).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("Pixelmon Grass").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "PixelmonGrass");;
		ShinglesBlock = new ShinglesBlock(ShinglesBlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeStone).setBlockName("Shingles").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "Shingles");;
		ShinglesCorner1Block = new ShinglesCorner1Block(ShinglesCorner1BlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeStone).setBlockName("Shingles Corner 1").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "RoofCorner1");;
		ShinglesCorner2Block = new ShinglesCorner2Block(ShinglesCorner2BlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeStone).setBlockName("Shingles Corner 2").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "RoofCorner2");;
		TreeTopBlock = new TreeTopBlock(TreeTopBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Tree Top").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "TreeTop");;
		TreeBottomBlock = new TreeBottomBlock(TreeBottomBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Tree Bottom").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" +":"+ "TreeBottom");;
		PokeSandSide1Block = new PokeSandSide1Block(PokeSandSide1BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandSide1").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "PokeSandSide1");;
		PokeSandSide2Block = new PokeSandSide2Block(PokeSandSide2BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandSide2").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "PokeSandSide2");;
		PokeSandSide3Block = new PokeSandSide3Block(PokeSandSide3BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandSide3").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "PokeSandSide3");;
		PokeSandSide4Block = new PokeSandSide4Block(PokeSandSide4BlockID, Material.sand).setHardness(0.5f).setStepSound(Block.soundTypeSand).setBlockName("PokeSandSide4").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "PokeSandSide4");;
		Window1Block = new Window1Block(Window1BlockID, Material.glass).setHardness(0.5f).setStepSound(Block.soundTypeGlass).setBlockName("Window1").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "Window");;
		Window2Block = new Window2Block(Window2BlockID, Material.glass).setHardness(0.5f).setStepSound(Block.soundTypeGlass).setBlockName("Window2").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "Window2");;
		WoodenFlooringBlock = new WoodenFlooringBlock(WoodenFlooringBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("WoodenFlooring").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "WoodenFlooring");;
		PokeCenterSignBlock = new PokeCenterSignBlock(PokeCenterSignBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("PokeCenterSign").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "Pokecenter");;
		PokeMartSignBlock = new PokeMartSignBlock(PokeMartSignBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("PokeMartSign").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "PokemartSign");;
		SandyGrassBlock = new SandyGrassBlock(SandyGrassBlockID, Material.grass).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("SandyGrass").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "SandyGrass");;
		RockBlock = new RockBlock(RockBlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("Rock").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "Rock");;
		CaveRockBlock = new CaveRockBlock(CaveRockBlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("CabeRock").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "CaveRock");;
		BridgeBlockBlock = new BridgeBlockBlock(BridgeBlockBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeGrass).setBlockName("BridgeBlock").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks).setBlockTextureName("PixelUtilitys" + ":" + "BridgeBlock");;
		TreeBlock = new TreeBlock(TreeBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Tree").setBlockTextureName("pixelutilitys:Tree");;
		BolderBlock = new BolderBlock(BolderBlockID, Material.rock).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Bolder").setBlockTextureName("pixelutilitys:Bolder");;
		BoxBlock = new BoxBlock(BoxBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("Box");;
		RubyOre = new RubyOre(RubyOreID, Material.rock).setHardness(1.5f).setStepSound(Block.soundTypeStone).setBlockName("RubyOre").setBlockTextureName("pixelutilitys:RubyOre");;
		SaphireOre = new SaphireOre(SaphireOreID, Material.rock).setHardness(1.5f).setStepSound(Block.soundTypeStone).setBlockName("SaphireOre").setBlockTextureName("pixelutilitys:SaphireOre");;
		AmethystOre = new AmethystOre(AmethystOreID, Material.rock).setHardness(1.5f).setStepSound(Block.soundTypeStone).setBlockName("AmethystOre").setBlockTextureName("pixelutilitys:AmethystOre");;
		CrystalOre = new CrystalOre(CrystalOreID, Material.rock).setHardness(1.5f).setStepSound(Block.soundTypeStone).setBlockName("CrystalOre").setBlockTextureName("pixelutilitys:CrystalOre");
		RubyBlock = new RubyBlock(RubyBlockID, Material.rock).setHardness(8.5f).setStepSound(Block.soundTypeMetal).setBlockName("RubyBlock").setBlockTextureName("pixelutilitys:RubyBlock").setCreativeTab(CreativeTabs.tabBlock);;
		SaphireBlock = new SaphireBlock(SaphireBlockID, Material.rock).setHardness(8.5f).setStepSound(Block.soundTypeMetal).setBlockName("SaphireBlock").setBlockTextureName("pixelutilitys:SaphireBlock").setCreativeTab(CreativeTabs.tabBlock);;
		AmethystBlock = new AmethystBlock(AmethystBlockID, Material.rock).setHardness(8.5f).setStepSound(Block.soundTypeMetal).setBlockName("AmethystBlock").setBlockTextureName("pixelutilitys:AmethystBlock").setCreativeTab(CreativeTabs.tabBlock);;
		CrystalBlock = new CrystalBlock(CrystalBlockID, Material.rock).setHardness(8.5f).setStepSound(Block.soundTypeMetal).setBlockName("CrystalBlock").setBlockTextureName("pixelutilitys:CrystalBlock").setCreativeTab(CreativeTabs.tabBlock);
		SiliconOre = new SiliconOre(SiliconOreID, Material.rock).setHardness(1.2f).setStepSound(Block.soundTypeMetal).setBlockName("SiliconOre").setBlockTextureName("pixelutilitys:SiliconOre").setCreativeTab(CreativeTabs.tabBlock);;
		ClothedTableBlock = new ClothedTableBlock(ClothedTableBlockID, Material.wood).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("ClothedTable");;
		PokeballBlock = new PokeballBlock(PokeballBlockID, Material.iron).setHardness(0.5f).setStepSound(Block.soundTypeMetal).setBlockName("Pokeball");;
		RedCusionChairBlock = new RedCusionChairBlock(RedCusionChairBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("RedCusionChair");;
		TrashcanBlock = new TrashcanBlock(TrashcanBlockID, Material.iron).setHardness(0.5f).setStepSound(Block.soundTypeMetal).setBlockName("Trashcan");;
		YellowCusionChairBlock = new YellowCusionChairBlock(YellowCusionChairBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeWood).setBlockName("YellowCusionChair");
		TotodilePokedollBlock = new TotodilePokedollBlock(TotodilePokedollBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeMetal).setBlockName("TotodileDoll");;
		//PokeWaterStill = new PokeWaterStill(PokeWaterStillID, Material.water).setBlockName("PokeWaterStill").setBlockTextureName("pixelutilitys:PokeWater").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks);
		//PokeWaterFlowing = new PokeWaterFlowing(PokeWaterFlowingID, Material.water).setBlockName("PokeWaterFlowing").setBlockTextureName("pixelutilitys:PokeWater").setCreativeTab(PixelUtilitysCreativeTabs.tabPixelmonBlocks);
		AronPokedollBlock = new AronPokedollBlock(AronPokedollBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeMetal).setBlockName("AronDoll");;
		BisharpPokedollBlock = new BisharpPokedollBlock(BisharpPokedollBlockID, Material.cloth).setHardness(0.5f).setStepSound(Block.soundTypeMetal).setBlockName("BisharpDoll");;
		RadioBlock = new BlockRadio(BlockRadioID, Material.wood);
	}
	public static void addNames() {

		GameRegistry.registerBlock(NewGrassBlock, "PokeGrass");
		//LanguageRegistry.addName(NewGrassBlock, "PokeGrass");
		GameRegistry.registerBlock(PokeSandBlock, "PokeSand");
		//LanguageRegistry.addName(PokeSandBlock, "PokeSand");
		GameRegistry.registerBlock(PokeSandC1Block, "PokeSandCorner1");
		//LanguageRegistry.addName(PokeSandC1Block, "PokeSandCorner1");
		GameRegistry.registerBlock(PokeSandC2Block, "PokeSandCorner2");
		//LanguageRegistry.addName(PokeSandC2Block, "PokeSandCorner2");
		GameRegistry.registerBlock(PokeSandC3Block, "PokeSandCorner3");
		//LanguageRegistry.addName(PokeSandC3Block, "PokeSandCorner3");
		GameRegistry.registerBlock(PokeSandC4Block, "PokeSandCorner4");
		//LanguageRegistry.addName(PokeSandC4Block, "PokeSandCorner4");
		GameRegistry.registerBlock(PokeDirtBlock, "PokeDirt");
		//LanguageRegistry.addName(PokeDirtBlock, "PokeDirt");
		GameRegistry.registerBlock(InsideMoldingBlock, "Inside Wall Molding");
		//LanguageRegistry.addName(InsideMoldingBlock, "Inside Wall Molding");
		GameRegistry.registerBlock(PixelmonGrassBlock, "Pixelmon Grass");
		//LanguageRegistry.addName(PixelmonGrassBlock, "Pixelmon Grass");
		GameRegistry.registerBlock(ShinglesCorner2Block, "Shingles Corner 2");
		//LanguageRegistry.addName(ShinglesCorner2Block, "Shingles Corner 2");
		GameRegistry.registerBlock(ShinglesBlock, "Shingles");
		//LanguageRegistry.addName(ShinglesBlock, "Shingles");
		GameRegistry.registerBlock(ShinglesCorner1Block, "Shingles Corner 1");
		//LanguageRegistry.addName(ShinglesCorner1Block, "Shingles Corner 1");
		GameRegistry.registerBlock(TreeTopBlock, "Tree Top");
		//LanguageRegistry.addName(TreeTopBlock, "Tree Top");
		GameRegistry.registerBlock(TreeBottomBlock, "Tree Bottom");
		//LanguageRegistry.addName(TreeBottomBlock, "Tree Bottom");
		GameRegistry.registerBlock(PokeSandSide1Block, "PokeSand Side 1");
		//LanguageRegistry.addName(PokeSandSide1Block, "PokeSand Side 1");
		GameRegistry.registerBlock(PokeSandSide2Block, "PokeSand Side 2");
		//LanguageRegistry.addName(PokeSandSide2Block, "PokeSand Side 2");
		GameRegistry.registerBlock(PokeSandSide3Block, "PokeSand Side 3");
		//LanguageRegistry.addName(PokeSandSide3Block, "PokeSand Side 3");
		GameRegistry.registerBlock(PokeSandSide4Block, "PokeSand Side 4");
		//LanguageRegistry.addName(PokeSandSide4Block, "PokeSand Side 4");
		GameRegistry.registerBlock(Window1Block, "Window 1");
		//LanguageRegistry.addName(Window1Block, "Window 1");
		GameRegistry.registerBlock(Window2Block, "Window 2");
		//LanguageRegistry.addName(Window2Block, "Window 2");
		GameRegistry.registerBlock(WoodenFlooringBlock, "Wooden Flooring");
		//LanguageRegistry.addName(WoodenFlooringBlock, "Wooden Flooring");
		GameRegistry.registerBlock(PokeCenterSignBlock, "PokeCenter Sign");
		//LanguageRegistry.addName(PokeCenterSignBlock, "PokeCenter Sign");
		GameRegistry.registerBlock(PokeMartSignBlock, "PokeMart Sign");
		//LanguageRegistry.addName(PokeMartSignBlock, "PokeMart Sign");
		GameRegistry.registerBlock(SandyGrassBlock, "Sandy Grass");
		//LanguageRegistry.addName(SandyGrassBlock, "Sandy Grass");
		GameRegistry.registerBlock(RockBlock, "Rock");
		//LanguageRegistry.addName(RockBlock, "Rock");
		GameRegistry.registerBlock(CaveRockBlock, "Cave Rock");
		//LanguageRegistry.addName(CaveRockBlock, "Cave Rock");
		GameRegistry.registerBlock(BridgeBlockBlock, "Bridge");
		//LanguageRegistry.addName(BridgeBlockBlock, "Bridge");
		GameRegistry.registerBlock(RubyBlock, "RubyBlock");
		//LanguageRegistry.addName(RubyBlock, "Ruby Block");
		GameRegistry.registerBlock(SaphireBlock, "SaphireBlock");
		//LanguageRegistry.addName(SaphireBlock, "Saphire Block");
		GameRegistry.registerBlock(AmethystBlock, "AmethystBlock");
		//LanguageRegistry.addName(AmethystBlock, "Amethyst Block");
		GameRegistry.registerBlock(CrystalBlock, "CrystalBlock");
		GameRegistry.registerBlock(TreeBlock, "Tree");
		//LanguageRegistry.addName(TreeBlock, "Tree");
		GameRegistry.registerBlock(BolderBlock, "Bolder");
		//LanguageRegistry.addName(BolderBlock, "Bolder");
		GameRegistry.registerBlock(BoxBlock, "Box");
		//LanguageRegistry.addName(BoxBlock, "Box");
		GameRegistry.registerBlock(ClothedTableBlock, "ClothedTable");
		//LanguageRegistry.addName(ClothedTableBlock, "Clothed Table");
		GameRegistry.registerBlock(PokeballBlock, "Pokeball");
		//LanguageRegistry.addName(PokeballBlock, "Placable Pokeball");
		GameRegistry.registerBlock(RedCusionChairBlock, "RedCusionChair");
		//LanguageRegistry.addName(RedCusionChairBlock, "Red Cusion Chair");
		GameRegistry.registerBlock(TrashcanBlock, "Trashcan");
		//LanguageRegistry.addName(TrashcanBlock, "Trashcan");
		GameRegistry.registerBlock(YellowCusionChairBlock, "YellowCusionChair");
		//LanguageRegistry.addName(YellowCusionChairBlock, "Yellow Cusion Chair");
		GameRegistry.registerBlock(SiliconOre, "SiliconOre");
		//LanguageRegistry.addName(SiliconOre, "Silicon Ore");
		GameRegistry.registerBlock(RubyOre, "RubyOre");
		GameRegistry.registerBlock(SaphireOre, "SaphireOre");
		GameRegistry.registerBlock(AmethystOre, "AmethystOre");
		GameRegistry.registerBlock(CrystalOre, "CrystalOre");
		//LanguageRegistry.addName(RubyOre, "Ruby Ore");
		//LanguageRegistry.addName(SaphireOre, "Saphire Ore");
		//LanguageRegistry.addName(AmethystOre, "Amethyst Ore");
		GameRegistry.registerBlock(TotodilePokedollBlock, "TotodileDoll");
		//LanguageRegistry.addName(TotodilePokedollBlock, "Totodile Pokedoll");
		GameRegistry.registerBlock(AronPokedollBlock, "AronDoll");
		//LanguageRegistry.addName(AronPokedollBlock, "Aron Pokedoll");
		GameRegistry.registerBlock(BisharpPokedollBlock, "BisharpDoll");
		//LanguageRegistry.addName(BisharpPokedollBlock, "Bisharp Pokedoll");
		GameRegistry.registerBlock(RadioBlock, "Radio");

		//GameRegistry.registerBlock(PokeWaterStill, "PokeWaterStill");
		//LanguageRegistry.addName(PokeWaterStill, "PokeWater Still");
		//GameRegistry.registerBlock(PokeWaterFlowing, "PokeWaterFlowing");
		//LanguageRegistry.addName(PokeWaterFlowing, "PokeWater Flowing");
	}

}