// Date: 2/7/2014 9:20:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.pixelutilitys.models.Pokedolls;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TotodilePokedollModel extends ModelBase {
    //fields
    ModelRenderer Body_Lower;
    ModelRenderer Body_Higher;
    ModelRenderer Leg_Base_Left;
    ModelRenderer Leg_Tip_Left;
    ModelRenderer Leg_Base_Right;
    ModelRenderer Leg_Tip_Right;
    ModelRenderer Lower_Jaw;
    ModelRenderer Head_Back;
    ModelRenderer Upper_Jaw;
    ModelRenderer Eye_Left;
    ModelRenderer Eye_Right;
    ModelRenderer Arm_Left;
    ModelRenderer Arm_Right;
    ModelRenderer Tail_base;
    ModelRenderer Tail_Middle;
    ModelRenderer Tail_Tip;
    ModelRenderer Shape1;
    ModelRenderer Shape2;

    public TotodilePokedollModel() {
        textureWidth = 64;
        textureHeight = 32;

        Body_Lower = new ModelRenderer(this, 0, 0);
        Body_Lower.addBox(-2.5F, 0F, -2.5F, 5, 4, 5);
        Body_Lower.setRotationPoint(0F, 20F, 0F);
        Body_Lower.setTextureSize(64, 32);
        Body_Lower.mirror = true;
        setRotation(Body_Lower, 0F, 0F, 0F);
        Body_Higher = new ModelRenderer(this, 0, 9);
        Body_Higher.addBox(-2F, -3F, -2F, 4, 3, 4);
        Body_Higher.setRotationPoint(0F, 20F, 0F);
        Body_Higher.setTextureSize(64, 32);
        Body_Higher.mirror = true;
        setRotation(Body_Higher, 0F, 0F, 0F);
        Leg_Base_Left = new ModelRenderer(this, 0, 16);
        Leg_Base_Left.addBox(-3.5F, 1F, 0.5F, 3, 3, 3);
        Leg_Base_Left.setRotationPoint(0F, 20F, 0F);
        Leg_Base_Left.setTextureSize(64, 32);
        Leg_Base_Left.mirror = true;
        setRotation(Leg_Base_Left, 0F, -0.2617994F, 0F);
        Leg_Tip_Left = new ModelRenderer(this, 12, 21);
        Leg_Tip_Left.addBox(-3F, -1.5F, 4F, 2, 4, 1);
        Leg_Tip_Left.setRotationPoint(0F, 20F, 0F);
        Leg_Tip_Left.setTextureSize(64, 32);
        Leg_Tip_Left.mirror = true;
        setRotation(Leg_Tip_Left, -0.3490659F, -0.2617994F, 0F);
        Leg_Base_Right = new ModelRenderer(this, 0, 22);
        Leg_Base_Right.addBox(0.5F, 1F, 0.5F, 3, 3, 3);
        Leg_Base_Right.setRotationPoint(0F, 20F, 0F);
        Leg_Base_Right.setTextureSize(64, 32);
        Leg_Base_Right.mirror = true;
        setRotation(Leg_Base_Right, 0F, 0.2617994F, 0F);
        Leg_Tip_Right = new ModelRenderer(this, 12, 21);
        Leg_Tip_Right.addBox(1F, -1.5F, 4F, 2, 4, 1);
        Leg_Tip_Right.setRotationPoint(0F, 20F, 0F);
        Leg_Tip_Right.setTextureSize(64, 32);
        Leg_Tip_Right.mirror = true;
        setRotation(Leg_Tip_Right, -0.3490659F, 0.2617994F, 0F);
        Lower_Jaw = new ModelRenderer(this, 34, 7);
        Lower_Jaw.addBox(-2F, -4F, -0.5F, 4, 1, 4);
        Lower_Jaw.setRotationPoint(0F, 20F, 0F);
        Lower_Jaw.setTextureSize(64, 32);
        Lower_Jaw.mirror = true;
        setRotation(Lower_Jaw, -0.2617994F, 0F, 0F);
        Head_Back = new ModelRenderer(this, 20, 0);
        Head_Back.addBox(-2F, -6F, -1.5F, 4, 3, 3);
        Head_Back.setRotationPoint(0F, 20F, 0F);
        Head_Back.setTextureSize(64, 32);
        Head_Back.mirror = true;
        setRotation(Head_Back, 0F, 0F, 0F);
        Upper_Jaw = new ModelRenderer(this, 34, 0);
        Upper_Jaw.addBox(-2F, -6F, 0.7F, 4, 2, 5);
        Upper_Jaw.setRotationPoint(0F, 20F, 0F);
        Upper_Jaw.setTextureSize(64, 32);
        Upper_Jaw.mirror = true;
        setRotation(Upper_Jaw, 0.2617994F, 0F, 0F);
        Eye_Left = new ModelRenderer(this, 20, 6);
        Eye_Left.addBox(-2F, -4.3F, 4.4F, 1, 3, 2);
        Eye_Left.setRotationPoint(0F, 20F, 0F);
        Eye_Left.setTextureSize(64, 32);
        Eye_Left.mirror = true;
        setRotation(Eye_Left, 1.047198F, 0F, 0F);
        Eye_Right = new ModelRenderer(this, 26, 6);
        Eye_Right.addBox(1F, -4.3F, 4.4F, 1, 3, 2);
        Eye_Right.setRotationPoint(0F, 20F, 0F);
        Eye_Right.setTextureSize(64, 32);
        Eye_Right.mirror = true;
        setRotation(Eye_Right, 1.047198F, 0F, 0F);
        Arm_Left = new ModelRenderer(this, 18, 23);
        Arm_Left.addBox(-3.5F, -0.7F, -1F, 1, 5, 2);
        Arm_Left.setRotationPoint(0F, 20F, 0F);
        Arm_Left.setTextureSize(64, 32);
        Arm_Left.mirror = true;
        setRotation(Arm_Left, 0F, 0F, 0.7853982F);
        Arm_Right = new ModelRenderer(this, 18, 16);
        Arm_Right.addBox(2.5F, -0.7F, -1F, 1, 5, 2);
        Arm_Right.setRotationPoint(0F, 20F, 0F);
        Arm_Right.setTextureSize(64, 32);
        Arm_Right.mirror = true;
        setRotation(Arm_Right, 0F, 0F, -0.7853982F);
        Tail_base = new ModelRenderer(this, 16, 11);
        Tail_base.addBox(-1.5F, 1F, -4.5F, 3, 3, 2);
        Tail_base.setRotationPoint(0F, 20F, 0F);
        Tail_base.setTextureSize(64, 32);
        Tail_base.mirror = true;
        setRotation(Tail_base, 0F, 0F, 0F);
        Tail_Middle = new ModelRenderer(this, 0, 28);
        Tail_Middle.addBox(-1F, 1.5F, -6.5F, 2, 2, 2);
        Tail_Middle.setRotationPoint(0F, 20F, 0F);
        Tail_Middle.setTextureSize(64, 32);
        Tail_Middle.mirror = true;
        setRotation(Tail_Middle, 0F, 0F, 0F);
        Tail_Tip = new ModelRenderer(this, 16, 9);
        Tail_Tip.addBox(-0.5F, 2F, -7.5F, 1, 1, 1);
        Tail_Tip.setRotationPoint(0F, 20F, 0F);
        Tail_Tip.setTextureSize(64, 32);
        Tail_Tip.mirror = true;
        setRotation(Tail_Tip, 0F, 0F, 0F);
        Shape1 = new ModelRenderer(this, 60, 28);
        Shape1.addBox(2.1F, -7F, -1F, 0, 2, 2);
        Shape1.setRotationPoint(0F, 20F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 60, 28);
        Shape2.addBox(-2.1F, -7F, -1F, 0, 2, 2);
        Shape2.setRotationPoint(0F, 20F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Body_Lower.render(f5);
        Body_Higher.render(f5);
        Leg_Base_Left.render(f5);
        Leg_Tip_Left.render(f5);
        Leg_Base_Right.render(f5);
        Leg_Tip_Right.render(f5);
        Lower_Jaw.render(f5);
        Head_Back.render(f5);
        Upper_Jaw.render(f5);
        Eye_Left.render(f5);
        Eye_Right.render(f5);
        Arm_Left.render(f5);
        Arm_Right.render(f5);
        Tail_base.render(f5);
        Tail_Middle.render(f5);
        Tail_Tip.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
