// Date: 12/8/2013 1:02:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.pixelutilitys.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BasicDeskModel extends ModelBase {
    //fields
    ModelRenderer DeskTop;
    ModelRenderer LegMiddle;
    ModelRenderer SideRight;
    ModelRenderer BackRight;
    ModelRenderer SideLeft;
    ModelRenderer DrawerTop;
    ModelRenderer DrawerBottom;
    ModelRenderer BackLeft;

    public BasicDeskModel() {
        textureWidth = 128;
        textureHeight = 64;

        DeskTop = new ModelRenderer(this, 0, 49);
        DeskTop.addBox(-15F, 0F, -6F, 30, 2, 13);
        DeskTop.setRotationPoint(8F, 8F, 0F);
        DeskTop.setTextureSize(128, 64);
        DeskTop.mirror = true;
        setRotation(DeskTop, 0F, 0F, 0F);
        LegMiddle = new ModelRenderer(this, 86, 38);
        LegMiddle.addBox(3F, 2F, -5F, 2, 14, 12);
        LegMiddle.setRotationPoint(8F, 8F, 0F);
        LegMiddle.setTextureSize(128, 64);
        LegMiddle.mirror = true;
        setRotation(LegMiddle, 0F, 0F, 0F);
        SideRight = new ModelRenderer(this, 86, 38);
        SideRight.addBox(-14F, 2F, -5F, 2, 14, 12);
        SideRight.setRotationPoint(8F, 8F, 0F);
        SideRight.setTextureSize(128, 64);
        SideRight.mirror = true;
        setRotation(SideRight, 0F, 0F, 0F);
        BackRight = new ModelRenderer(this, 13, 51);
        BackRight.addBox(-12F, 2F, 6F, 15, 10, 1);
        BackRight.setRotationPoint(8F, 8F, 0F);
        BackRight.setTextureSize(128, 64);
        BackRight.mirror = true;
        setRotation(BackRight, 0F, 0F, 0F);
        SideLeft = new ModelRenderer(this, 86, 38);
        SideLeft.addBox(12F, 2F, -5F, 2, 14, 12);
        SideLeft.setRotationPoint(8F, 8F, 0F);
        SideLeft.setTextureSize(128, 64);
        SideLeft.mirror = true;
        setRotation(SideLeft, 0F, 0F, 0F);
        DrawerTop = new ModelRenderer(this, 0, 34);
        DrawerTop.addBox(5F, 2F, -4.5F, 7, 5, 10);
        DrawerTop.setRotationPoint(8F, 8F, 0F);
        DrawerTop.setTextureSize(128, 64);
        DrawerTop.mirror = true;
        setRotation(DrawerTop, 0F, 0F, 0F);
        DrawerBottom = new ModelRenderer(this, 0, 34);
        DrawerBottom.addBox(5F, 7.1F, -4.5F, 7, 5, 10);
        DrawerBottom.setRotationPoint(8F, 8F, 0F);
        DrawerBottom.setTextureSize(128, 64);
        DrawerBottom.mirror = true;
        setRotation(DrawerBottom, 0F, 0F, 0F);
        BackLeft = new ModelRenderer(this, 13, 51);
        BackLeft.addBox(5F, 2F, 6F, 7, 10, 1);
        BackLeft.setRotationPoint(8F, 8F, 0F);
        BackLeft.setTextureSize(128, 64);
        BackLeft.mirror = true;
        setRotation(BackLeft, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        DeskTop.render(f5);
        LegMiddle.render(f5);
        SideRight.render(f5);
        BackRight.render(f5);
        SideLeft.render(f5);
        DrawerTop.render(f5);
        DrawerBottom.render(f5);
        BackLeft.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
