// Date: 12/24/2013 5:25:23 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.pixelutilitys.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BolderModel extends ModelBase {
    //fields
    ModelRenderer BolderBass;
    ModelRenderer Bolder2;
    ModelRenderer Bolder3;
    ModelRenderer Bolder4;

    public BolderModel() {
        textureWidth = 64;
        textureHeight = 32;

        BolderBass = new ModelRenderer(this, 0, 16);
        BolderBass.addBox(0F, 0F, 0F, 12, 4, 12);
        BolderBass.setRotationPoint(-6F, 20F, -6F);
        BolderBass.setTextureSize(64, 32);
        BolderBass.mirror = true;
        setRotation(BolderBass, 0F, 0F, 0F);
        Bolder2 = new ModelRenderer(this, 0, 4);
        Bolder2.addBox(0F, 0F, 0F, 10, 2, 10);
        Bolder2.setRotationPoint(-5F, 18F, -5F);
        Bolder2.setTextureSize(64, 32);
        Bolder2.mirror = true;
        setRotation(Bolder2, 0F, 0F, 0F);
        Bolder3 = new ModelRenderer(this, 32, 0);
        Bolder3.addBox(0F, 0F, 0F, 8, 2, 8);
        Bolder3.setRotationPoint(-4F, 16F, -4F);
        Bolder3.setTextureSize(64, 32);
        Bolder3.mirror = true;
        setRotation(Bolder3, 0F, 0F, 0F);
        Bolder4 = new ModelRenderer(this, 40, 18);
        Bolder4.addBox(0F, 0F, 0F, 6, 1, 6);
        Bolder4.setRotationPoint(-3F, 15F, -3F);
        Bolder4.setTextureSize(64, 32);
        Bolder4.mirror = true;
        setRotation(Bolder4, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        BolderBass.render(f5);
        Bolder2.render(f5);
        Bolder3.render(f5);
        Bolder4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
