// Date: 12/27/2013 1:25:28 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.pixelutilitys.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BoxModel extends ModelBase {
    //fields
    ModelRenderer MainBox;
    ModelRenderer Flap1;
    ModelRenderer Flap2;

    public BoxModel() {
        textureWidth = 64;
        textureHeight = 64;

        MainBox = new ModelRenderer(this, 0, 0);
        MainBox.addBox(0F, 0F, 0F, 16, 14, 16);
        MainBox.setRotationPoint(-8F, 10F, -8F);
        MainBox.setTextureSize(64, 64);
        MainBox.mirror = true;
        setRotation(MainBox, 0F, 0F, 0F);
        Flap1 = new ModelRenderer(this, 0, 46);
        Flap1.addBox(-8F, -1F, -8F, 8, 2, 16);
        Flap1.setRotationPoint(8F, 10F, 0F);
        Flap1.setTextureSize(64, 64);
        Flap1.mirror = true;
        setRotation(Flap1, 0F, 0F, 0F);
        Flap2 = new ModelRenderer(this, 0, 28);
        Flap2.addBox(0F, -1F, -8F, 8, 2, 16);
        Flap2.setRotationPoint(-8F, 10F, 0F);
        Flap2.setTextureSize(64, 64);
        Flap2.mirror = true;
        setRotation(Flap2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        MainBox.render(f5);
        Flap1.render(f5);
        Flap2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
